apiVersion: v1
kind: Service
metadata:
  name: "semaphoreupdatebot"
  labels:
    app.kubernetes.io/name: "Semaphoreupdatebot"
spec:
  ports:
    - name: "semaphoreupdatebot-http"
      protocol: "TCP"
      port: 8080
      targetPort: "app"
  selector:
    app.kubernetes.io/name: "semaphoreupdatebot"
